import AppProvider from '@/providers/AppProvider';
import type { Metadata } from 'next';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
import SubNavbar from './components/Navbar/SubNavbar';
import '@/services/firebase/firebase.service';
import './globals.css';
import { NextUIProvider } from '@nextui-org/react';
import 'rsuite/dist/rsuite.min.css';

export const metadata: Metadata = {
  title: 'Distress Sale',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="max-w-[1450px] mx-auto">
        {/* <NextUIProvider> */}
          <AppProvider>
            {/* <Navbar /> */}
            {/* <SubNavbar /> */}
            {children}
            <Footer />
          </AppProvider>
        {/* </NextUIProvider> */}
      </body>
    </html>
  );
}
