import AppProvider from '@/providers/AppProvider';
import type { Metadata } from 'next';
import Footer from './components/Footer/Footer';
import Navbar from './components/Navbar/Navbar';
import SubNavbar from './components/Navbar/SubNavbar';
import '@/services/firebase/firebase.service';
import './globals.css';

export const metadata: Metadata = {
  title: 'Distress Sale',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Navbar />
          <SubNavbar />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
